import { Request, Response } from 'express';
import { prisma } from '../index';
import { sendWhatsAppMessage } from '../services/whatsappService';

// @desc    Create a new consultation
// @route   POST /api/doctor/consultation
// @access  Private (Doctor)
export const createConsultation = async (req: Request, res: Response): Promise<void> => {
  const { queueId, patientId, symptoms, diagnosis, notes } = req.body;
  const doctorId = (req as any).user.id;

  try {
    const consultation = await prisma.consultation.create({
      data: {
        patientId,
        doctorId,
        symptoms,
        diagnosis,
        notes,
      },
    });

    // Mark Queue as COMPLETED
    if (queueId) {
      await prisma.queue.update({
        where: { id: queueId },
        data: { status: 'COMPLETED' },
      });
    }

    res.status(201).json({ success: true, data: consultation });
  } catch (error) {
    res.status(500).json({ message: 'Server error creating consultation' });
  }
};

// @desc    Create a prescription
// @route   POST /api/doctor/prescription
// @access  Private (Doctor)
export const createPrescription = async (req: Request, res: Response): Promise<void> => {
  const { consultationId, items } = req.body;
  // items: Array of { medicineId, dosage, duration, quantity }

  try {
    const consultation = await prisma.consultation.findUnique({
      where: { id: consultationId },
      include: { patient: true },
    });

    if (!consultation) {
      res.status(404).json({ message: 'Consultation not found' });
      return;
    }

    const prescription = await prisma.prescription.create({
      data: {
        consultationId,
        items: {
          create: items.map((item: any) => ({
            medicineId: item.medicineId,
            dosage: item.dosage,
            duration: item.duration,
            quantity: item.quantity,
          })),
        },
      },
      include: { items: true },
    });

    await sendWhatsAppMessage(
      consultation.patient.phone,
      `Hello ${consultation.patient.name}, your prescription has been generated by the doctor. Please proceed to the pharmacy to collect your medicines.`
    );

    res.status(201).json({ success: true, data: prescription });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: 'Server error creating prescription' });
  }
};
